group_relation.config.invitation_expire:
  type: 'integer'
  label: 'Expire invites'

group_relation.config.invitation_expire_keep:
  type: 'boolean'
  label: Keep expired invitations'

group_relation.config.invitation_subject:
  type: 'text'
  label: 'Subject'

group_relation.config.invitation_body:
  type: 'text'
  label: 'Body'

group_relation.config.existing_user_invitation_subject:
  type: 'text'
  label: 'Subject'

group_relation.config.existing_user_invitation_body:
  type: 'text'
  label: 'Body'

group_relation.config.unblock_invitees:
  type: 'boolean'
  label: 'Unblock invitees'

group_relation.config.invitation_bypass_form:
  type: 'boolean'
  label: 'Accept invitations immediately'

group_relation.config.cancel_user_invitation_subject:
  type: 'text'
  label: 'Subject'

group_relation.config.cancel_user_invitation_body:
  type: 'text'
  label: 'Body'

group_relation.config.send_cancel_email:
  type: 'boolean'
  label: 'Send notification when an invitation is cancelled'

group_relation.config.send_email_existing_users:
  type: 'boolean'
  label: 'Send invitation e-mail to already registered users'

group_relation.config.send_email_not_existing_users:
  type: 'boolean'
  label: 'Send invitation e-mail to invitee'

group_relation.config.remove_invitation:
  type: 'integer'
  label: 'Remove an invitation, when user join the group.'

group_relation.config.autoaccept_invitees:
  type: 'boolean'
  label: 'Automatically accept invitation'

ginvite.pending_invitations_warning:
  type: config_object
  label: Pending invitations warning settings
  mapping:
    excluded_routes:
      type: sequence
      nullable: false
      label: Exclude routes where this warning is redundant or would generate confusion
      sequence:
        type: string
    warning_message:
      label: The warning message about pending invitations
      type: text
