data_policy.informblock.*:
  type: config_entity
  label: 'Inform Block config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    page:
      type: string
      label: 'Page'
    status:
      type: boolean
      label: 'Status'
    summary:
      type: mapping
      label: 'Summary'
      mapping:
        value:
          type: text
          label: 'Value'
        format:
          type: string
          label: 'Format'
    body:
      type: mapping
      label: 'Body'
      mapping:
        value:
          type: text
          label: 'Value'
        format:
          type: string
          label: 'Format'
